"""update_schema_to_content_embeddings

Revision ID: 27cfcd70f4db
Revises: b465b49579fe
Create Date: 2025-06-22 15:46:20.410215

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "27cfcd70f4db"
down_revision: str | Sequence[str] | None = "b465b49579fe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content_embeddings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_document", sa.String(length=255), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("content_text", sa.Text(), nullable=False),
        sa.Column(
            "content_vector", sa.Text(), nullable=True
        ),  # Use TEXT for now, can be converted to VECTOR later
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_content_embeddings_id"), "content_embeddings", ["id"], unique=False)
    op.create_index(
        op.f("ix_content_embeddings_page_number"),
        "content_embeddings",
        ["page_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_content_embeddings_source_document"),
        "content_embeddings",
        ["source_document"],
        unique=False,
    )
    op.drop_index(op.f("ix_charity_policies_id"), table_name="charity_policies")
    op.drop_table("charity_policies")
    op.drop_column("query_logs", "created_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "query_logs",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_table(
        "charity_policies",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("doc_metadata", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("charity_policies_pkey")),
    )
    op.create_index(op.f("ix_charity_policies_id"), "charity_policies", ["id"], unique=False)
    op.drop_index(op.f("ix_content_embeddings_source_document"), table_name="content_embeddings")
    op.drop_index(op.f("ix_content_embeddings_page_number"), table_name="content_embeddings")
    op.drop_index(op.f("ix_content_embeddings_id"), table_name="content_embeddings")
    op.drop_table("content_embeddings")
    # ### end Alembic commands ###
