"""create_initial_content_embeddings_table

Revision ID: b465b49579fe
Revises:
Create Date: 2025-06-22 15:32:46.624647

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b465b49579fe"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "charity_policies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("doc_metadata", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_charity_policies_id"), "charity_policies", ["id"], unique=False)
    op.create_table(
        "query_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("query_text", sa.Text(), nullable=False),
        sa.Column("response_text", sa.Text(), nullable=True),
        sa.Column("session_id", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_query_logs_id"), "query_logs", ["id"], unique=False)
    op.drop_index(op.f("charity_policies_idx_1"), table_name="data_charity_policies")
    op.drop_table("data_charity_policies")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_charity_policies",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("text", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "metadata_", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("node_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("embedding", sa.NullType(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("data_charity_policies_pkey")),
    )
    op.create_index(
        op.f("charity_policies_idx_1"),
        "data_charity_policies",
        [sa.literal_column("(metadata_ ->> 'ref_doc_id'::text)")],
        unique=False,
    )
    op.drop_index(op.f("ix_query_logs_id"), table_name="query_logs")
    op.drop_table("query_logs")
    op.drop_index(op.f("ix_charity_policies_id"), table_name="charity_policies")
    op.drop_table("charity_policies")
    # ### end Alembic commands ###
